### ISSUE TITLE
How to represent VersionCode in the MedCom FHIR messages 

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom#45]
The versionCode represents the version of the profile. 
The task is to find the FHIR way to handle the version id

**Comment by tmh-mjolner** [comment]
The FHIR way is described here (snippet from https://www.hl7.org/fhir/versioning.html#mp-version). Are we sure that we want to do this? @medcomire @ovi-medcom 

2.8.3 Version Specific Profile 
There are some circumstances where applications handle 'naked' resources - that is, resources where there is no wrapping envelope to carry a mimetype version parameter, nor any suitable parallel location to store the version. The most obvious circumstance is when resources are stored in files, though this may arise in other circumstances due to (legacy) application or protocol design.

When there's no other alternative, the version has to be in the resources itself, and applications reading the resource have to scan the resource to determine the version and then read the resource as the correct version.

In these cases where the version must be placed in the resource itself, this is done by indicating that the resource conforms to specific version in meta.profile:

{
  "resourceType" : "Patient",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/3.0/StructureDefinition/Patient"]
  }
}

**Comment by medcomire** [comment]
We have to define a place for us and vendors to unified inspect the version of the FHIR message.

**Comment by MedComAnders** [comment]
Issue fixet in #69 
1.0 has been added to the URI
